@startuml

+class AAUOC {
    newLocation(l : Location) : void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}
class Location {
    description : String
    address : String
}
class Event {
    date : Date
    description : String
    assign(l : Location) : void

}
class Member {
    e-mail : String
}
class Person {
    name : String
}
class Conference {
    max_attendees : Integer
}

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- "0..*" Location
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person

Location "1" -- "0..*" Event :IsLocated In
Event "0..*" -- "0..*" Member :attendsTo
BoardMeeting "0..*" -- "0..*" BoardMember :attendsTo
Conference "0..*" -- "0..*" Person :attendsTo

@enduml