@startuml

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person

Location -- Event
Event -- Member
BoardMeeting -- BoardMember
Conference -- Person


@enduml